@echo off
REM ════════════════════════════════════════════════════════════════════════════
REM SETUP_WIZARD.bat - Interactive configuration assistant
REM ════════════════════════════════════════════════════════════════════════════

setlocal enabledelayedexpansion

cls
echo.
echo ╔════════════════════════════════════════════════════════════════════════╗
echo ║             TRADING BRAINS MT5 - SETUP WIZARD                          ║
echo ║                        VERSION 5.0.0                                   ║
echo ╚════════════════════════════════════════════════════════════════════════╝
echo.

REM Check Python
python --version >nul 2>&1
if errorlevel 1 (
    echo ❌ ERROR: Python not found. Please install Python 3.9+
    pause
    exit /b 1
)

REM Check venv
if not exist venv (
    echo Installing virtual environment...
    python -m venv venv
    call venv\Scripts\activate.bat
    pip install -q -r requirements.txt
) else (
    call venv\Scripts\activate.bat
)

echo.
echo 📋 CONFIGURATION WIZARD
echo ═══════════════════════
echo.

REM Symbol
set /p SYMBOL="Enter trading symbol (e.g., EURUSD): "
if "!SYMBOL!"=="" set SYMBOL=EURUSD

REM Timeframes
echo.
echo Available timeframes: M1, M5, M15, M30, H1, H4, D1
set /p TIMEFRAMES="Enter timeframes (comma-separated, e.g., H1,H4): "
if "!TIMEFRAMES!"=="" set TIMEFRAMES=H1,H4

REM Risk per trade
set /p RISK="Enter risk per trade %% (default 1.0): "
if "!RISK!"=="" set RISK=1.0

REM Daily loss limit
set /p DAILY_LOSS="Enter daily loss limit %% (default 2.0): "
if "!DAILY_LOSS!"=="" set DAILY_LOSS=2.0

REM Daily profit target
set /p DAILY_PROFIT="Enter daily profit target %% (0=disabled, default 0): "
if "!DAILY_PROFIT!"=="" set DAILY_PROFIT=0

REM Max trades per day
set /p MAX_TRADES="Enter max trades per day (default 10): "
if "!MAX_TRADES!"=="" set MAX_TRADES=10

REM Max trades per hour
set /p MAX_HOUR="Enter max trades per hour (default 3): "
if "!MAX_HOUR!"=="" set MAX_HOUR=3

echo.
echo 🔧 GENERATING CONFIGURATION...
echo.

REM Create .env from template
(
    echo REM Generated by SETUP_WIZARD.bat
    echo REM Generated at: %date% %time%
    echo.
    echo SYMBOL=%SYMBOL%
    echo TIMEFRAMES=%TIMEFRAMES%
    echo RISK_PER_TRADE=%RISK%
    echo DAILY_LOSS_LIMIT=%DAILY_LOSS%
    echo DAILY_PROFIT_TARGET=%DAILY_PROFIT%
    echo MAX_TRADES_PER_DAY=%MAX_TRADES%
    echo MAX_TRADES_PER_HOUR=%MAX_HOUR%
    echo.
    echo REM Default settings
    echo LIVE_MODE=SIM
    echo REQUIRE_LIVE_OK_FILE=true
    echo COOLDOWN_SECONDS=180
    echo DEGRADE_STEPS=3
    echo DEGRADE_FACTOR=0.5
    echo BREAK_EVEN_AFTER_TP1=true
    echo TRAILING_ENABLED=false
    echo TRAILING_ATR_MULT=1.5
    echo STALE_DATA_MINUTES=3
    echo MT5_RECONNECT_MAX_SECONDS=60
    echo FILL_MODEL_SPREAD_BASE=1.0
    echo FILL_MODEL_SLIPPAGE_MAX=2.0
    echo USE_PARTIAL_EXITS=false
    echo FALLBACK_ON_MT5_ERROR=PAUSE
) > .env

echo ✅ Configuration saved to .env

echo.
echo 🔍 RUNNING HEALTH CHECK...
python -m src.main healthcheck

if errorlevel 1 (
    echo.
    echo ❌ Health check failed. Please verify your MT5 setup and symbol.
    pause
    exit /b 1
)

echo.
echo ✅ Setup complete!
echo.
echo Next steps:
echo 1. Review .env file for any adjustments
echo 2. Run RUN_LIVE_SIM.bat to start paper trading
echo 3. Run RUN_TESTS.bat to verify installation
echo.
echo For live trading, see V4_SECURITY_CHECKLIST.txt
echo.

pause
