"""
Market Status Engine - IA Trabalhando em Tempo Real

Gera status do mercado combinando informações de:
- Regime Detection (L3)
- Uncertainty Gates (L2)
- Liquidity Analysis (L4)
- Cross-Market (L6)
- Macro Brain (H1)
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from datetime import datetime
from enum import Enum
from typing import Optional, Dict, List, Any
import logging

logger = logging.getLogger(__name__)


class RiskState(Enum):
    """Risk state of the market."""
    OK = "OK"
    CAUTION = "CAUTION"
    BLOCKED = "BLOCKED"


@dataclass
class MarketStatus:
    """Current market status generated by AI."""
    
    timestamp: datetime
    symbol: str
    headline: str  # Ex: "Tendência de alta confirmada"
    phase: str  # Ex: "Aguardando pullback para compra"
    risk_state: str  # "OK" | "CAUTION" | "BLOCKED"
    reasons: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict for JSON serialization."""
        return {
            'timestamp': self.timestamp.isoformat(),
            'symbol': self.symbol,
            'headline': self.headline,
            'phase': self.phase,
            'risk_state': self.risk_state,
            'reasons': self.reasons,
            'metadata': self.metadata
        }


@dataclass
class MarketStatusContext:
    """Context for status generation."""
    
    symbol: str
    regime: Optional[str] = None  # TREND_UP, TREND_DOWN, RANGE, TRANSITION, CHAOTIC
    transition_active: bool = False
    ensemble_confidence: Optional[float] = None  # 0-1
    conformal_coverage: Optional[float] = None  # 0-1
    model_disagreement: Optional[float] = None  # 0-1
    
    liquidity_strength: Optional[float] = None  # 0-1
    zone_proximity: Optional[str] = None  # NEAR_TP, NEAR_SL, SAFE, NEUTRAL
    volatility_level: Optional[str] = None  # LOW, NORMAL, HIGH, EXTREME
    
    cross_signal_type: Optional[str] = None  # CONFIRM_BUY, REDUCE_BUY, MARKET_BROKEN, etc
    cross_correlation: Optional[float] = None  # -1 to 1
    news_blocked: bool = False
    news_risk_factor: Optional[float] = None  # 0.5 = reduced, 1.0 = normal
    
    macro_signal: Optional[str] = None  # BUY, SELL, NEUTRAL
    macro_phase: Optional[str] = None  # ACCUMULATION, MARKUP, DISTRIBUTION, MARKDOWN


class MarketStatusEngine:
    """
    Generates market status using multiple signals.
    
    Combines L3 regime, L2 uncertainty, L4 liquidity, L6 cross-market, macro signals.
    """
    
    def __init__(self):
        pass
    
    def generate_status(self, context: MarketStatusContext) -> MarketStatus:
        """
        Generate market status from context.
        
        Args:
            context: MarketStatusContext with all available signals
        
        Returns:
            MarketStatus with headline, phase, risk_state, and reasons
        """
        now = datetime.now()
        
        # Determine headline based on regime and signals
        headline = self._generate_headline(context)
        
        # Determine current phase
        phase = self._determine_phase(context)
        
        # Calculate risk state
        risk_state = self._calculate_risk_state(context)
        
        # Collect reasons
        reasons = self._collect_reasons(context)
        
        # Build metadata
        metadata = self._build_metadata(context)
        
        return MarketStatus(
            timestamp=now,
            symbol=context.symbol,
            headline=headline,
            phase=phase,
            risk_state=risk_state,
            reasons=reasons,
            metadata=metadata
        )
    
    def _generate_headline(self, context: MarketStatusContext) -> str:
        """Generate main headline based on regime and signals."""
        
        # If news blocked, override everything
        if context.news_blocked:
            return "🚫 Bloqueado por evento econômico"
        
        # If market broken correlation
        if context.cross_signal_type == 'MARKET_BROKEN':
            return "⚠️ Correlação quebrada - Mercado desalinhado"
        
        # Base on regime
        if context.regime == 'TREND_UP':
            if context.cross_signal_type == 'CONFIRM_BUY':
                return "📈 Tendência de ALTA confirmada (multi-mercado)"
            elif context.cross_signal_type in ['REDUCE_BUY', 'REDUCE_SELL']:
                return "📈 Tendência de ALTA (alerta de redução)"
            return "📈 Tendência de ALTA confirmada"
        
        elif context.regime == 'TREND_DOWN':
            if context.cross_signal_type == 'CONFIRM_SELL':
                return "📉 Tendência de BAIXA confirmada (multi-mercado)"
            elif context.cross_signal_type in ['REDUCE_SELL', 'REDUCE_BUY']:
                return "📉 Tendência de BAIXA (alerta de redução)"
            return "📉 Tendência de BAIXA confirmada"
        
        elif context.regime == 'RANGE':
            if context.zone_proximity == 'NEAR_TP':
                return "📊 Em range - Próximo ao suporte para compra"
            elif context.zone_proximity == 'NEAR_SL':
                return "📊 Em range - Próximo à resistência para venda"
            return "📊 Mercado em range - Aguardando breakout"
        
        elif context.regime == 'TRANSITION':
            return "🔄 Em transição de regime - Prudência recomendada"
        
        elif context.regime == 'CHAOTIC':
            return "🌪️ Mercado caótico - Alto risco de sinalização falsa"
        
        # Default
        return "❓ Status incerto - Coletar mais dados"
    
    def _determine_phase(self, context: MarketStatusContext) -> str:
        """Determine current trading phase."""
        
        # If blocked
        if context.news_blocked:
            return f"Aguardando liberação (risco reduzido {context.news_risk_factor:.0%})"
        
        # If transition
        if context.transition_active:
            return "Transição de regime em progresso - Esperar confirmação"
        
        # If high disagreement or low confidence
        if context.model_disagreement and context.model_disagreement > 0.25:
            return "Incerteza elevada no ensemble - Aguardar confirmação adicional"
        
        if context.ensemble_confidence and context.ensemble_confidence < 0.55:
            return "Confiança baixa - Não há sinal claro, aguardando"
        
        # If in range
        if context.regime == 'RANGE':
            if context.zone_proximity == 'NEAR_TP':
                return "Próximo ao suporte - Buscando setup de compra"
            elif context.zone_proximity == 'NEAR_SL':
                return "Próximo à resistência - Buscando setup de venda"
            return "Em consolidação - Aguardando breakout"
        
        # If trend with good liquidity
        if context.regime in ['TREND_UP', 'TREND_DOWN']:
            if context.liquidity_strength and context.liquidity_strength > 0.7:
                return f"Seguindo tendência com liquidez forte - Pronto para {context.regime}"
            elif context.liquidity_strength and context.liquidity_strength > 0.5:
                return f"Seguindo tendência - Liquidez moderada"
            else:
                return f"Tendência fraca em liquidez - Cuidado com stops"
        
        # High volatility caution
        if context.volatility_level == 'EXTREME':
            return "Volatilidade extrema - Reduzir posição ou aguardar"
        
        return "Mercado normal - Aguardando setup de entrada"
    
    def _calculate_risk_state(self, context: MarketStatusContext) -> str:
        """Calculate overall risk state."""
        
        # BLOCKED takes absolute priority
        if context.news_blocked:
            return RiskState.BLOCKED.value
        
        if context.cross_signal_type == 'MARKET_BROKEN':
            return RiskState.BLOCKED.value
        
        if context.regime == 'CHAOTIC':
            return RiskState.BLOCKED.value
        
        # CAUTION - elevated risk
        caution_flags = 0
        caution_threshold = 2
        
        if context.transition_active:
            caution_flags += 1
        
        if context.regime == 'TRANSITION':
            caution_flags += 1
        
        if context.model_disagreement and context.model_disagreement > 0.20:
            caution_flags += 1
        
        if context.ensemble_confidence and context.ensemble_confidence < 0.65:
            caution_flags += 1
        
        if context.cross_signal_type in ['REDUCE_BUY', 'REDUCE_SELL']:
            caution_flags += 1
        
        if context.volatility_level in ['HIGH', 'EXTREME']:
            caution_flags += 1
        
        if context.liquidity_strength and context.liquidity_strength < 0.4:
            caution_flags += 1
        
        if caution_flags >= caution_threshold:
            return RiskState.CAUTION.value
        
        # OK - normal trading
        return RiskState.OK.value
    
    def _collect_reasons(self, context: MarketStatusContext) -> List[str]:
        """Collect reasons for current status."""
        reasons = []
        
        # Regime
        if context.regime:
            regime_map = {
                'TREND_UP': '✓ Tendência para cima confirmada',
                'TREND_DOWN': '✓ Tendência para baixo confirmada',
                'RANGE': '⊙ Mercado consolidando',
                'TRANSITION': '🔄 Transição de regime',
                'CHAOTIC': '✗ Mercado caótico/desorganizado'
            }
            if context.regime in regime_map:
                reasons.append(regime_map[context.regime])
        
        # Confidence
        if context.ensemble_confidence:
            if context.ensemble_confidence > 0.75:
                reasons.append(f'✓ Ensemble: {context.ensemble_confidence:.0%} confiança')
            elif context.ensemble_confidence > 0.55:
                reasons.append(f'⊙ Ensemble: {context.ensemble_confidence:.0%} confiança moderada')
            else:
                reasons.append(f'✗ Ensemble: {context.ensemble_confidence:.0%} confiança baixa')
        
        # Model disagreement
        if context.model_disagreement:
            if context.model_disagreement < 0.15:
                reasons.append(f'✓ Consenso: modelos alinhados ({context.model_disagreement:.1%} desacordo)')
            elif context.model_disagreement < 0.25:
                reasons.append(f'⊙ Modelos com leve desacordo ({context.model_disagreement:.1%})')
            else:
                reasons.append(f'✗ Desacordo alto entre modelos ({context.model_disagreement:.1%})')
        
        # Liquidity
        if context.liquidity_strength:
            if context.liquidity_strength > 0.7:
                reasons.append(f'✓ Liquidez forte: {context.liquidity_strength:.0%}')
            elif context.liquidity_strength > 0.5:
                reasons.append(f'⊙ Liquidez moderada: {context.liquidity_strength:.0%}')
            else:
                reasons.append(f'✗ Liquidez fraca: {context.liquidity_strength:.0%}')
        
        # Cross-market
        if context.cross_signal_type:
            if context.cross_signal_type.startswith('CONFIRM'):
                reasons.append(f'✓ Multi-mercado confirma sinal')
            elif context.cross_signal_type.startswith('REDUCE'):
                reasons.append(f'⊙ Multi-mercado: reduzir confiança')
            elif context.cross_signal_type == 'MARKET_BROKEN':
                reasons.append(f'✗ Correlação quebrada')
        
        # News
        if context.news_blocked:
            reasons.append(f'🚫 Evento econômico: {context.news_risk_factor:.0%} risco')
        
        # Volatility
        if context.volatility_level == 'EXTREME':
            reasons.append(f'⚠️ Volatilidade extrema')
        elif context.volatility_level == 'HIGH':
            reasons.append(f'⊙ Volatilidade elevada')
        
        # Macro
        if context.macro_signal:
            macro_map = {
                'BUY': '📈 Macro: sinal de compra',
                'SELL': '📉 Macro: sinal de venda',
                'NEUTRAL': '⊙ Macro: sem sinal claro'
            }
            if context.macro_signal in macro_map:
                reasons.append(macro_map[context.macro_signal])
        
        return reasons if reasons else ["⊙ Aguardando mais dados para análise"]
    
    def _build_metadata(self, context: MarketStatusContext) -> Dict[str, Any]:
        """Build metadata dictionary."""
        return {
            'regime': context.regime,
            'transition_active': context.transition_active,
            'ensemble_confidence': context.ensemble_confidence,
            'conformal_coverage': context.conformal_coverage,
            'model_disagreement': context.model_disagreement,
            'liquidity_strength': context.liquidity_strength,
            'zone_proximity': context.zone_proximity,
            'volatility_level': context.volatility_level,
            'cross_signal_type': context.cross_signal_type,
            'cross_correlation': context.cross_correlation,
            'news_blocked': context.news_blocked,
            'news_risk_factor': context.news_risk_factor,
            'macro_signal': context.macro_signal,
            'macro_phase': context.macro_phase
        }
